# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89e3f6f881d32bdd12d5e09324c0fae2a726a2c248098f8b9486298229fa6ec1ba5663500cb4a280d77a5a71060b2102eb193750eaf41736b0add065471bfcaf

test:
  secret_key_base: d1250bc8b5fb057e580ca1ab1e9fbb1b47480b852c856fbda093056178b748c7ab03b05f6ad2d8266dc43bbcb928ce0103bdb6f83dcb54294c339f4a13bd79d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
